export const GET_COORDINATES_SUCCESS = 'GET_COORDINATES_SUCCESS';
export type GET_COORDINATES_SUCCESS = typeof GET_COORDINATES_SUCCESS;

export const GET_COORDINATES_FAILED = 'GET_COORDINATES_FAILED';
export type GET_COORDINATES_FAILED = typeof GET_COORDINATES_FAILED;

export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export type GET_LOCATION_SUCCESS = typeof GET_LOCATION_SUCCESS;

export const GET_LOCATION_FAILED = 'GET_LOCATION_FAILED';
export type GET_LOCATION_FAILED = typeof GET_LOCATION_FAILED;

export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS';
export type GET_WEATHER_DATA_SUCCESS = typeof GET_WEATHER_DATA_SUCCESS;

export const GET_WEATHER_DATA_FAILED = 'GET_WEATHER_DATA_FAILED';
export type GET_WEATHER_DATA_FAILED = typeof GET_WEATHER_DATA_FAILED;

export const GET_FORECAST_DATA_SUCCESS = 'GET_FORECAST_DATA_SUCCESS';
export type GET_FORECAST_DATA_SUCCESS = typeof GET_FORECAST_DATA_SUCCESS;

export const GET_FORECAST_DATA_FAILED = 'GET_FORECAST_DATA_FAILED';
export type GET_FORECAST_DATA_FAILED = typeof GET_FORECAST_DATA_FAILED;

/*
const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
const AJAX_CALL_END = 'AJAX_CALL_END';
const ERROR_HAPPENED = 'ERROR_HAPPENED';*/
