export const GET_CURRENT_USER_COORDINATES_SUCCESS = 'GET_CURRENT_USER_COORDINATES_SUCCESS';
export type GET_CURRENT_USER_COORDINATES_SUCCESS = typeof GET_CURRENT_USER_COORDINATES_SUCCESS;

export const GET_CURRENT_USER_COORDINATES_FAILED = 'GET_CURRENT_USER_COORDINATES_FAILED';
export type GET_CURRENT_USER_COORDINATES_FAILED = typeof GET_CURRENT_USER_COORDINATES_FAILED;

export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS';
export type GET_WEATHER_DATA_SUCCESS = typeof GET_WEATHER_DATA_SUCCESS;

export const GET_WEATHER_DATA_FAILED = 'GET_WEATHER_DATA_FAILED';
export type GET_WEATHER_DATA_FAILED = typeof GET_WEATHER_DATA_FAILED;