export const SET_LOCATION_SUCCESS = 'SET_LOCATION_SUCCESS';
export type SET_LOCATION_SUCCESS = typeof SET_LOCATION_SUCCESS;

export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export type FETCH_WEATHER_START = typeof FETCH_WEATHER_START;

export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export type FETCH_WEATHER_SUCCESS = typeof FETCH_WEATHER_SUCCESS;

export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';
export type FETCH_WEATHER_FAILURE = typeof FETCH_WEATHER_FAILURE;

export const FETCH_FORECAST_START = 'FETCH_FORECAST_START';
export type FETCH_FORECAST_START = typeof FETCH_FORECAST_START;

export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
export type FETCH_FORECAST_SUCCESS = typeof FETCH_FORECAST_SUCCESS;

export const FETCH_FORECAST_FAILURE = 'FETCH_FORECAST_FAILURE';
export type FETCH_FORECAST_FAILURE = typeof FETCH_FORECAST_FAILURE;

export const ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY';
export type ADD_FAVORITE_CITY = typeof ADD_FAVORITE_CITY;

export const REMOVE_FAVORITE_CITY = 'REMOVE_FAVORITE_CITY';
export type REMOVE_FAVORITE_CITY = typeof REMOVE_FAVORITE_CITY;